background {
    monitor =
    path = $HOME/wallpapers/wallhaven-wypg9r.jpg
    blur_passes = 3
    blur_size = 7
    brightness = 0.8
}

# Día de la semana — arriba, grande, blanco
label {
    monitor =
    text = cmd[update:60000] LC_TIME=C date +"%A" | tr '[:lower:]' '[:upper:]' | sed 's/./& /g;s/ $//'
    color = rgba(ffffffff)
    font_size = 120
    font_family = Blanka
    position = 0, 160
    halign = center
    valign = center
}

# Hora — abajo del día, con espaciado
label {
    monitor =
    text = cmd[update:1000] date +"%I:%M" | sed 's/./& /g;s/ $//'
    color = rgba(ffffffff)
    font_size = 100
    font_family = Blanka
    position = 0, 20
    halign = center
    valign = center
}

# Input de contraseña
input-field {
    monitor =
    size = 200, 70
    outline_thickness = 0
    inner_color = rgba(00000088)
    font_color = rgb(ffffff)
    font_family = JetBrains Mono
    placeholder_text = <span></span>
    fade_on_empty = false
    hide_input = false
    rounding = 40
    position = 0, -180
    halign = center
    valign = center
}
